# docker-compose.yml (Versão para MySQL)
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: gameverse-db-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SenhaRoot2705!93 # Senha para o usuário root do MySQL
      MYSQL_DATABASE: gameverse_db_mysql  # Nome do banco de dados que será criado
      MYSQL_USER: gameverse_app # Nome do usuário da aplicação
      MYSQL_PASSWORD: Senh@F0rt&345# # Senha para o usuário da aplicação
    ports:
      - "3306:3306" # Porta padrão do MySQL
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
